### ISSUE TITLE
请问asn1.io/asn1playground这个网址怎么使用

### ISSUE THREAD

**Issue by betterqiang** [xuanxuanblingbling/cv2x#1]
您好，能请教下，这个网址如何上传您的v2x.asn 文件以及如何解析这个编码么00016626466686a6c6e700001246654268f3dc631a51400000001f91f91fdfffc00140140000

感谢

**Comment by betterqiang** [comment]
目前的操作如下：
1.
![截图_20230808154216](https://github.com/xuanxuanblingbling/cv2x/assets/122032889/a5e3943b-5352-4cb1-b435-7ceb14fa99b9)
2.
![截图_20230808154303](https://github.com/xuanxuanblingbling/cv2x/assets/122032889/65227bad-3713-4688-949b-431b9c13048b)
3.
![截图_20230808154353](https://github.com/xuanxuanblingbling/cv2x/assets/122032889/45ce11df-4445-429b-aad8-7ae4cb12906a)
报文没有被解析出来··

**Comment by xuanxuanblingbling** [comment]
这个网站貌似现在需要登录了，你登录一下，其实是解析成功了的，解析的结果在右下角的txt或者json中

Qiang ***@***.***> 于2023年8月8日周二 14:24写道：
